[package]
name = "blitz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slab = "0.4.9"
style = { workspace = true }
euclid = { version = "0.22", features = ["serde"] }
selectors = { workspace = true }
taffy = { workspace = true }
tokio = { workspace = true, features = ["full"] }
vello = { workspace = true }
wgpu = { workspace = true }
shipyard = { version = "0.6.2", features = [
    "proc",
    "std",
], default-features = false }

app_units = "0.7.5"
atomic_refcell = { version = "0.1.13", features = ["serde"] }
fxhash = "0.2.1"
html5ever = "0.26.0"                                          # also conveniently the one used in servo
markup5ever_rcdom = "0.2.0"
string_cache = "0.8.7"
futures-util = "0.3.30"
raw-window-handle = "0.6.0"
blitz-dom = { path = "../dom" }
quadtree_rs = "0.1.3"
askama_escape = "0.10.3"
