[package]
name = "dioxus-blitz"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tao = { version = "0.26.1", features = ["serde"] }
muda = { version = "0.12.0", features = ["serde"] }
tokio = { workspace = true, features = ["full"] }
dioxus = { workspace = true }
dioxus-ssr = { workspace = true }
futures-util = "0.3.30"
vello = { workspace = true }
wgpu = { workspace = true }
style = { workspace = true }
blitz = { path = "../blitz" }
blitz-dom = { path = "../dom" }

[target."cfg(target_os = \"windows\")".dependencies.windows-sys]
version = "0.52"
features = [
  "Win32_UI_WindowsAndMessaging",
  "Win32_Foundation",
  "Win32_Graphics_Gdi",
  "Win32_UI_Shell",
  "Win32_Globalization",
  "Win32_UI_Input_KeyboardAndMouse",
  "Win32_System_SystemServices",
  "Win32_UI_Accessibility",
  "Win32_UI_HiDpi",
  "Win32_System_LibraryLoader",
  "Win32_UI_Controls"
]