[package]
name = "dioxus-blitz"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tao = { version = "0.26.1", features = ["serde"] }
muda = { version = "0.11.5", features = ["serde"] }
tokio = { workspace = true, features = ["full"] }
dioxus = { workspace = true }
dioxus-ssr = { workspace = true }
futures-util = "0.3.30"
vello = { workspace = true }
wgpu = { workspace = true }
style = { workspace = true }
blitz = { path = "../blitz" }
blitz-dom = { path = "../dom" }
url = { version = "2.5.0", features = ["serde"] }
ureq = "2.9"
rustc-hash = "1.1.0"
